server:
  port: 4000
spring:
  application:
    name: crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

short:
  message:
    access-key-id: "LTAI5tBcYomt7am5cpb3EoSW"
    access-secret: "2JwUnwbVJFmnSgPWLPBg3nyjTNLrFn"
    endpoint: "dysmsapi.aliyuncs.com"

# 由于项目刚启动第一次进行redis操作时会比较慢，可能被ribbon认为是超时报错，因此通过下面的配置延长ribbon超时的时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000




